{% set name = "ydb-dbapi" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ydb_dbapi-{{ version }}.tar.gz
  sha256: fcf485c3c782d7ee3840239892e1c27217b53a19efcc289fa8218440f9413f6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - ydb >=3.21.6,<4.0.0

test:
  imports:
    - ydb_dbapi
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ydb-platform/ydb-python-dbapi/
  summary: YDB Python DBAPI which complies with PEP 249
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/ydb-platform/ydb-python-dbapi/
  doc_url: https://github.com/ydb-platform/ydb-python-dbapi/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
