schema_version: 1

context:
  name: ydb-dbapi
  version: 0.1.18

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ydb_dbapi-${{ version }}.tar.gz
  sha256: 186e6fa05b809219866009e4ad5604324c7f89e9748166502dba4e5b34a81864

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - ydb >=3.24.0,<4.0.0
tests:
  - python:
      imports:
        - ydb_dbapi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: YDB Python DBAPI which complies with PEP 249
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ydb-platform/ydb-python-dbapi/
  repository: https://github.com/ydb-platform/ydb-python-dbapi/
  documentation: https://github.com/ydb-platform/ydb-python-dbapi/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
