schema_version: 1

context:
  name: ydb-dbapi
  version: 0.1.20

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ydb_dbapi-${{ version }}.tar.gz
  sha256: e373e4669513811cb6b56e71aed79f4c164c346724e4d11e2892482f965efc2d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - ydb >=3.26.7,<4.0.0
tests:
  - python:
      imports:
        - ydb_dbapi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: YDB Python DBAPI which complies with PEP 249
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ydb-platform/ydb-python-dbapi/
  repository: https://github.com/ydb-platform/ydb-python-dbapi/
  documentation: https://github.com/ydb-platform/ydb-python-dbapi/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
